language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install
services:
  - mysql

env:
  global:
    - NODE_ENV=test

before_script:
  - mysql -u root -e 'CREATE DATABASE nodejs_core_test;'
  - mysql -u root -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis';"
  - mysql -u root -e "GRANT ALL ON nodejs_core_test.* TO 'travis'@'localhost';"
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
