language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install
sudo: false
services:
  - mysql

env:
  global:
    - NODE_ENV=test

before_install:
  - mysql -e 'create database nodejs_core_test;'
  - mysql -u root -e "create user root identified by 'secret'; grant all on nodejs_core_test.* to root;"
  - mysql -u root -e "create user root@localhost identified by 'secret'; grant all on nodejs_core_test.* to root@localhost;"
  - mysql -u root -p'secret' -e 'show databases'
  - mysql -e 'select VERSION()'
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
