language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install
services:
  - mysql

env:
  global:
    - NODE_ENV=test

before_script:
  - sudo mysql -e "create database nodejs_core_test;"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p root
  - sudo service mysql restart
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
