version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: nodejs_core_development
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~